[package]
name = "melbi-values"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
melbi-types.workspace = true
static_assertions.workspace = true
bumpalo.workspace = true
