[package]

# TODO: fix compilation errors and remove the line below.
autotests = false

name = "melbi-parser"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
